name: Projeto Terraform Azure
on: 
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest     

    steps:
      - name: Cache
        uses: actions/cache@v3.3.2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Iniciando Terraform
        run: terraform init 

      - name: Planejando Terraform
        id: plan
        run: terraform plan      

      - name: Aplicando Terraform
        run: terraform apply -auto-approve   
        env: 
          client_id: "${{ secrets.CLIENT_ID }}"
          client_secret: "${{ secrets.CLIENT_SECRET}}"
          subscription_id: "${{ secrets.SUBS_ID }}"
          tenant_id: "${{ secrets.TENANTID }}"     

      - name: Destruindo Terraform
        run: terraform destroy -auto-approve
